version: '3.8'
services:
  npb-app-dev:
    image: npb-app-dev
    container_name: npb-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    # command: sleep infinity
    ports:
      - '3001:3001'
    volumes:
      - ./:/app
      - npb-app-dev-node_modules:/app/node_modules
      - npb-app-dev-next:/app/.next
    env_file:
      - ./envs/development-docker/.env.development.docker
      - ./envs/development-docker/.env.development.docker.local
    depends_on:
      - npb-db-dev
    networks:
      - internal-dev

  npb-db-dev:
    image: postgres:14.3-bullseye
    container_name: npb-db-dev
    restart: unless-stopped
    ports:
      - '5432:5432'
    user: '${MY_UID}:${MY_GID}'
    volumes:
      - ./prisma/pg-data:/var/lib/postgresql/data
    # only: POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB
    environment:
      - PGDATA=/var/lib/postgresql/data/data-dev
    env_file:
      - ./envs/development-docker/.env.development.docker.local
    networks:
      - internal-dev
      - external-host

  adminer-dev:
    image: 'adminer:4.8.1-standalone'
    container_name: adminer-dev
    ports:
      - '8080:8080'
    depends_on:
      - npb-db-dev
    networks:
      - internal-dev
      - external-host

volumes:
  npb-app-dev-node_modules:
  npb-app-dev-next:

networks:
  internal-dev:
    external: false
  external-host:
    external: true
