version: '3.8'
services:
  nextjs-prisma:
    container_name: nextjs-prisma-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3001:3001'
    # forward secrets from host at runtime
    environment:
      - CONTAINER_VAR=${HOST_VAR}
