version: '3.8'
services:
  npb-app-dev:
    container_name: npb-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    # command: sleep infinity
    ports:
      - '3001:3001'
    volumes:
      - ./:/app
      - npb-dev-node_modules:/app/node_modules
      - npb-dev-next:/app/.next
    env_file:
      - .env.development
      - .env.local
    depends_on:
      - npb-db-dev
    networks:
      - internal-dev

  npb-db-dev:
    image: postgres:14-alpine
    container_name: npb-db-dev
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - ./prisma/pg-data-dev:/var/lib/postgresql/data
    # instead of env_file
    # environment:
    #   POSTGRES_USER=$POSTGRES_USER
    #   POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    #   POSTGRES_DB=$POSTGRES_DB
    env_file:
      - .env.local
    networks:
      - internal-dev
      - external-host

  adminer-dev:
    image: 'adminer:4.8.1-standalone'
    container_name: adminer-dev
    ports:
      - '8080:8080'
    depends_on:
      - npb-db-dev
    networks:
      - internal-dev
      - external-host

volumes:
  npb-dev-node_modules:
  npb-dev-next:

networks:
  internal-dev:
    external: false
  external-host:
    external: true
