version: '3.8'
services:
  nextjs-prisma:
    container_name: nextjs-prisma-dev
    build:
      dockerfile: Dockerfile.dev

    ports:
      - '3001:3001'

    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next

    env_file:
      - .env.local
