version: '3.8'
services:
  nextjs-prisma-dev:
    container_name: nextjs-prisma-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    # command: sleep infinity
    ports:
      - '3001:3001'
    volumes:
      - ./:/app
      - np-dev-node_modules:/app/node_modules
      - np-dev-next:/app/.next
    env_file:
      - .env.development
      - .env.local
    depends_on:
      - postgres-db-dev
    networks:
      - internal

  postgres-db-dev:
    image: postgres:14-alpine
    container_name: postgres-db-dev
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - ./prisma/pg-data:/var/lib/postgresql/data
    # instead of env_file
    # environment:
    #   POSTGRES_USER=$POSTGRES_USER
    #   POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    #   POSTGRES_DB=$POSTGRES_DB
    env_file:
      - .env.local
    networks:
      - internal

  adminer-dev:
    image: 'adminer:4.8.1-standalone'
    container_name: adminer-dev
    ports:
      - '8080:8080'
    depends_on:
      - postgres-db-dev
    networks:
      - internal

volumes:
  np-dev-node_modules:
  np-dev-next:

networks:
  internal:
    external: false
