version: '3.8'
services:
  npb-app-test:
    container_name: npb-app-test
    build:
      context: .
      dockerfile: Dockerfile.test
    # container:app-process
    ports:
      - '3005:3001'
    #command: sleep infinity
    volumes:
      # must see src changes, frontend build prod
      - ./:/app
      - npb-test-node_modules:/app/node_modules
      - npb-test-next:/app/.next
      - npb-test-dist:/app/dist
    env_file:
      - .env.test
      - .env.test.local
    depends_on:
      - npb-db-test
    networks:
      - internal-test

  npb-db-test:
    image: postgres:14-alpine
    container_name: npb-db-test
    restart: unless-stopped
    ports:
      - '5435:5432'
    volumes:
      - ./prisma/pg-data-test:/var/lib/postgresql/data
    env_file:
      - .env.test.local
    networks:
      - internal-test

volumes:
  npb-test-node_modules:
  npb-test-next:
  npb-test-dist:

networks:
  internal-test:
    external: false
