version: '3.8'

# extends docker-compose.test.yml

services:
  npb-app-test:
    # entrypoint: sh -c 'whoami && id'
    # add
    command: yarn docker:test:start
    # override
    container_name: npb-app-e2e
    env_file:
      - ./envs/test-docker/.env.test.docker
      - ./envs/test-docker/.env.test.docker.local

  # reused
  # npb-db-test:

  npb-e2e:
    image: npb-e2e
    container_name: npb-e2e
    build:
      # must be in root to include prisma
      context: .
      dockerfile: Dockerfile.e2e
    depends_on:
      - npb-app-test
    env_file:
      - ./envs/test-docker/.env.test.docker
      - ./envs/test-docker/.env.test.docker.local
    # /app/package.json
    command: yarn test
    # entrypoint: whoami && id
    # command: sleep infinity
    # only tests can be edited without rebuilding
    # imports from next.js app are copied in Dockerfile
    # app is prod built anyway
    volumes:
      - ./tests-e2e/cypress:/app/tests-e2e/cypress
      - ./tests-e2e/cypress.json:/app/tests-e2e/cypress.json
    networks:
      - internal-test
