version: '3.8'
services:
  nextjs-prisma:
    container_name: nextjs-prisma-prod
    build:
      dockerfile: Dockerfile.prod

    ports:
      - '3001:3001'

    # runtime secrets
    env_file:
      - .env.local
