version: '3.8'
services:
  npb-app-test:
    container_name: npb-app-test
    build:
      context: .
      dockerfile: Dockerfile.test
    # container:app-process
    ports:
      - '3001:3001'
    #command: sleep infinity
    volumes:
      # must see src changes, frontend build prod
      - ./:/app
      - npb-test-node_modules:/app/node_modules
      - npb-test-next:/app/.next
      - npb-test-dist:/app/dist
    env_file:
      - .env.test
      - .env.test.local
    depends_on:
      - npb-db-test
    networks:
      - internal-test

  npb-db-test:
    image: postgres:14-alpine
    container_name: npb-db-test
    restart: unless-stopped
    # change internal port
    command: postgres -p 5435
    # expose it to host
    ports:
      - '5435:5435'
    volumes:
      - ./prisma/pg-data-test:/var/lib/postgresql/data
    env_file:
      - .env.test.local
    networks:
      - internal-test
      - external-host

  npb-e2e:
    image: npb-e2e
    build:
      context: ./tests-e2e
      dockerfile: Dockerfile
    container_name: npb-e2e
    depends_on:
      - npb-app-test
    environment:
      - CYPRESS_baseUrl=http://npb-app-test
    command: npx cypress run
    volumes:
      - ./tests-e2e/cypress:/app/cypress
      - ./tests-e2e/cypress.json:/app/cypress.json
    networks:
      - internal-test

volumes:
  npb-test-node_modules:
  npb-test-next:
  npb-test-dist:

networks:
  internal-test:
    external: false
  # for adminer dev d-c
  external-host:
    external: true
