version: '3.8'
services:
  npb-app-prod:
    image: npb-app-prod
    container_name: npb-app-prod
    # all that is needed to build prod live image
    build:
      context: .
      dockerfile: Dockerfile.prod
      # db needed for static site generation - getStaticProps
      args:
        - ARG_DATABASE_URL=$DATABASE_URL
        - ARG_NEXTAUTH_URL=$NEXTAUTH_URL

    # ports:
    #   - '3001:3001'
    #command: sleep infinity
    volumes:
      - ./uploads:/app/uploads
      # needed only for sqlite and db.dev
      # - ./prisma:/app/prisma
    # runtime only
    env_file:
      - ./envs/production-docker/.env.production.docker
      - ./envs/production-docker/.env.production.docker.local
      # - ./envs/production-live/.env.production.live
      # - ./envs/production-live/.env.production.live.local
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.nextjs-prisma-secure.rule=Host(`${SITE_HOSTNAME}`)'
      - 'traefik.http.routers.nextjs-prisma-secure.entrypoints=websecure'
      - 'traefik.http.routers.nextjs-prisma-secure.service=nextjs-prisma-svc'
      - 'traefik.http.services.nextjs-prisma-svc.loadbalancer.server.port=3001'
    depends_on:
      - npb-db-prod
    networks:
      - proxy
      - internal-prod

  npb-db-prod:
    image: postgres:14.3-bullseye
    container_name: npb-db-prod
    restart: unless-stopped
    ports:
      - '5432:5432'
    user: '${MY_UID}:${MY_GID}'
    volumes:
      - ./prisma/pg-data:/var/lib/postgresql/data
    # uncomment for external access
    # - ./prisma/pg-config/pg_hba.conf:/etc/postgresql.conf
    # - ./prisma/pg-config/postgresql.conf:/etc/pg_hba.conf

    environment:
      - PGDATA=/var/lib/postgresql/data/data-prod
      # instead of env_file
      # POSTGRES_USER=$POSTGRES_USER
      # POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      # POSTGRES_DB=$POSTGRES_DB
    env_file:
      - ./envs/production-docker/.env.production.docker.local
    networks:
      - proxy
      - internal-prod

networks:
  proxy:
    external: true
  internal-prod:
    external: false
