version: '3.8'
services:
  npb-app-prod:
    image: npb-app-prod
    container_name: npb-app-prod
    # all that is needed to build prod live image
    build:
      context: .
      dockerfile: Dockerfile.prod
      # DATABASE_URL needed for static site generation - getStaticProps
      # NEXTAUTH_URL needed for CustomHead SEO
      args:
        - ARG_DATABASE_URL=$DATABASE_URL
        - ARG_NEXTAUTH_URL=$NEXTAUTH_URL
    ports:
      - '3001:3001'
    #command: sleep infinity
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - ./envs/production-docker/.env.production.docker
      - ./envs/production-docker/.env.production.docker.local
    depends_on:
      - npb-db-prod
    networks:
      - proxy
      - internal-prod

  npb-db-prod:
    image: postgres:14.3-bullseye
    container_name: npb-db-prod
    restart: unless-stopped
    ports:
      - '5432:5432'
    user: '${MY_UID}:${MY_GID}'
    volumes:
      - ./prisma/pg-data:/var/lib/postgresql/data
    # uncomment for external access
    # - ./prisma/pg-config/pg_hba.conf:/etc/postgresql.conf
    # - ./prisma/pg-config/postgresql.conf:/etc/pg_hba.conf
    environment:
      - PGDATA=/var/lib/postgresql/data/data-prod
    env_file:
      - ./envs/production-docker/.env.production.docker.local
    networks:
      - proxy
      - internal-prod

networks:
  proxy:
    external: true
  internal-prod:
    external: false
