name: Build and push Docker image

on:
  push:
    branches:
      - 'production/oracle-amd'
  pull_request:
    branches:
      - 'production/oracle-amd'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: .
          file: ./Dockerfile.prod
          build-args: ARG_DATABASE_URL=${{ secrets.NPB_DATABASE_URL}}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nextjs-prisma-boilerplate:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/nextjs-prisma-boilerplate:buildcache
          cache-to: type=inline

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
